version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - ls $CODEBUILD_SRC_DIR
      
  build:
    commands:
      - liquibase --defaultsFile=liquibase.properties flow --flow-file=flows/build-flow.yaml
      
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'src'

