version: 0.2
    
env:
  secrets-manager:
    LIQUIBASE_COMMAND_USERNAME: LIQUIBASE-AWS-DEMO:username
    LIQUIBASE_COMMAND_PASSWORD: LIQUIBASE-AWS-DEMO:password
    LIQUIBASE_PRO_LICENSE_KEY: LIQUIBASE-PRO-KEY:KEY

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - ls $CODEBUILD_SRC_DIR
      
  build:
    commands:
      - liquibase --defaultsFile=liquibase.properties flow --flow-file=flows/build-flow.yaml
      - zip lb-aws-demo-build-$CODEBUILD_BUILD_NUMBER.zip $CODEBUILD_SRC_DIR/src
      
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - lb-aws-demo-build-$CODEBUILD_BUILD_NUMBER.zip

