version: 0.2
    
env:
  variables:
    LIQUIBASE_COMMAND_USERNAME: lbuser
    LIQUIBASE_COMMAND_PASSWORD: 1AmGr00t
    LIQUIBASE_COMMAND_URL: jdbc:mysql://lb-aws-demo-db-test.cft5wkyp4znj.us-east-1.rds.amazonaws.com:3306/sample
  secrets:
    LIQUIBASE_PRO_LICENSE_KEY: LIQUIBASE-PRO-KEY:KEY

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - ls $CODEBUILD_SRC_DIR
      
  build:
    commands:
      - liquibase --defaultsFile=liquibase.properties flow --flow-file=flows/build-flow.yaml
      
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'src'

